name:                yacp
version:             0.1.0.0
github:              "maxhbr/yacp"
license:             BSD3
author:              "Maximillian Huber"
maintainer:          "gh@maxhbr.de"
copyright:           "Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxhbr/yacp#readme>

dependencies:
- base >= 4.7 && < 5
# data types
- text
- bytestring
- Cabal # for SDPX expressions
- spdx # for SDPX.Extra
- uuid
- network-uri # URI
# containers
- vector
- hashable
- containers
- unordered-containers
# file path stuff
- directory
- filepath
# parsing and file handling
- aeson
- aeson-pretty
# output
- diagrams-graphviz
# misc
- mtl
- random
- pretty-terminal
- split

# - attoparsec
# - base16-bytestring
# - cassava
# - cryptohash-md5
# - curl
# - extra
# - file-embed
# - graphviz
# - hexml
# - http-client
# - lens
# - lens-aeson
# - lucid
# - mtl
# - network-uri
# - opensource
# - pandoc
# - pandoc-types
# - raw-strings-qq
# - yaml

library:
  source-dirs: src

executables:
  yacp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yacp

tests:
  yacp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yacp
    - hspec
    - QuickCheck
    - file-embed
