name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - uses: cachix/install-nix-action@v12
    # - uses: cachix/cachix-action@v8
    #   with:
    #     name: maxhbr
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1.1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.stack-work') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: stack build
    - name: Install plantuml
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml
    - name: Run tests
      run: stack test
    - name: Run yacp-exe
      run: |
        mkdir _tmp
        ./runExample.sh
    - uses: actions/upload-artifact@v2
      with:
        name: exec-yacp-exe-result
        path: _tmp
    - uses: actions/upload-artifact@v2
      with:
        name: exec-yacp-exe-result
        path: _tmp/plantuml.svg
